### ISSUE TITLE
Wrong check on Content Type header

### ISSUE THREAD

**Issue by Raffo** [ionos-cloud/external-dns-ionos-webhook#10]
Hi, I'm @Raffo, the author of the ExternalDNS plugin provider. I want to thank you again for giving me access to this plugin and to IONOS to test it out. 

I have tried to adapt my end to end testing framework to include this plugin and I hit a problem which I think is a bug in the code. 

The docs of the plugin provider say:

> Additionally, the server needs to respond to `GET` requests on `/` to negotiate versions by content type as described in [this document](http://opensource.zalando.com/restful-api-guidelines/#114). The server needs to respond to those requests by reading the `Accept` header and responding with a corresponding `Vary` header including the value `Content-Type` and a `Content-Type` header specifying the supported media type format and version.

But your code is checking this: https://github.com/ionos-cloud/external-dns-ionos-plugin/blob/main/pkg/plugin/plugin.go#L199

```
func (p *Plugin) ApplyChanges(w http.ResponseWriter, r *http.Request) {
	if p.hasContentHeader(w, r) {
```

The content type should be set by the "server" which in this case is the IONOS provider. ExternalDNS is **not** setting any Content Type for all requests. I'm following those instructions for the logic: http://opensource.zalando.com/restful-api-guidelines/#114 

I did instead add a commit that adds the accept header to all requests even though I originally had it only for the negotiation phase. I think it makes sense and this plugin helped me spot that problem. 

Let me know what you think of this and if it makes sense. 

Thanks! 

/cc @akrieg-ionos @mspoeri

**Comment by akrieg-ionos** [comment]
Thanks, for testing and giving your feedback! With [this comment](https://github.com/kubernetes-sigs/external-dns/pull/3063#discussion_r1219352975) the api content negotiation has been specified, and [release 0.3.0 ](https://github.com/ionos-cloud/external-dns-ionos-webhook/releases/tag/v0.3.0) is implementing this.
