### ISSUE TITLE
`external-dns-ionos-webhook` returns occasional EOF to ExternalDNS

### ISSUE THREAD

**Issue by Raffo** [ionos-cloud/external-dns-ionos-webhook#22]
## Description

I'm posting this after the previous email exchange, to make sure that it is tracked here and it has all the information with the visibility that is needed.

I did some testing with the latest build of ExternalDNS from the webhook branch (which you can pull from `x0rg/external-dns:plugin`) and I saw the following problem: from time to time, the pod crashes due to an EOF in talking with the ionos webhook. Given that everything is running on localhost that is particularly interesting.

What I see in the ExternalDNS logs is:

```
time="2023-06-27T03:15:22Z" level=fatal msg="Get \"[http://localhost:8888/records\](http://localhost:8888/records%5C)": EOF"
```

And the restarts over a few days are quite a few:

```
NAME                                 READY   STATUS    RESTARTS   AGE
external-dns-797cc979b5-jr289        2/2     Running   50         2d17h 
```

I think there could be something wrong on the webhook side of things, but I am not sure. I'd appreciate some feedback if you get the chance to do some testing. Thanks a lot!

**Comment by akrieg-ionos** [comment]
@Raffo thanks for reporting! Finally I was able to see the issue also on our deployment. I don't know the root cause for this yet, but for now i can that there seems no backend (dns provider problem) related to this, here our container logs:
```log
2023-07-06 05:00:33.361	
{"level":"fatal","msg":"Get \"http://localhost:8888/records\": EOF","time":"2023-07-06T03:00:33Z"}
2023-07-06 05:00:33.361	
{"level":"debug","msg":"Failed to perform request: Get \"http://localhost:8888/records\": EOF","time":"2023-07-06T03:00:33Z"}

2023-07-06 05:00:33.360	
{"level":"debug","msg":"returning records count: 13","requestMethod":"GET","requestPath":"/records","time":"2023-07-06T03:00:33Z"}
```

**Comment by Raffo** [comment]
Interesting that this is happening to you too. I will try to dig more to get at the bottom of the issue.

**Comment by akrieg-ionos** [comment]
Unfortunately the issue is still  present also in our latest release. However it only occurs when using the ionos-core dns backend.

**Comment by akrieg-ionos** [comment]
Finally, I found the problem of EOF: The root cause are long lasting calls to the DNS backend. In some cases the backend itself returns 503. However we would expect  the webhook should return with 5xx to external-dns. The reason why this is not happening is a configured server timeout in the webhook. In the the [release v0.6.0](https://github.com/ionos-cloud/external-dns-ionos-webhook/releases/tag/v0.6.0) there is no default server timeout. With this release I have not seen this phenom any more.
