### ISSUE TITLE
Invalid JWT check

### ISSUE THREAD

**Issue by hans-fischer** [ionos-cloud/external-dns-ionos-webhook#40]
In the file: cmd/webhook/init/dnsprovider/dnsprovider.go

You are checking for iss = ionoscloud.
That check is not valid. We get a jwt issued by bechtlecloud when we getting a ionos-cloud jwt.

Could you please correct the problem so we can use your webhook?

Kind regards
Hans Fischer

**Comment by akrieg-ionos** [comment]
@hans-fischer thanks for your feedback, currently we are checking this issue, i will keep you up to date regarding this, i am quite sure that we have a solution for you very soon.

**Comment by akrieg-ionos** [comment]
using image [v0.6.1](https://github.com/ionos-cloud/external-dns-ionos-webhook/releases/tag/v0.6.1) should fix the problem
